### ISSUE TITLE
unpack(): Type n: not enough input, need 2, have 0 in php-font-lib\src\FontLib\Binary_Stream.php on line 183

### ISSUE THREAD

**Issue by fitoe** [dompdf/php-font-lib#47] opened 2016-02-17 06:37 UTC
With the font "4YEOstamp.ttf","2 Prong Tree.TTF", In the "Unicode map", there is an error:

> unpack(): Type n: not enough input, need 2, have 0 in php-font-lib\src\FontLib\Binary_Stream.php on line 183

~[!Y2KBUG.zip](http://www.font.hk/phenx/!Y2KBUG.zip)~
~[2 Prong Tree.zip](http://www.font.hk/phenx/2%20Prong%20Tree.zip)~
## 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30932723-unpack-type-n-not-enough-input-need-2-have-0-in-php-font-lib-src-fontlib-binary_stream-php-on-line-183?utm_campaign=plugin&utm_content=tracker%2F317728&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F317728&utm_medium=issues&utm_source=github).

**Comment by bsweeney** [comment] 2016-02-17 23:12
Relevant discussion on the dompdf support group: https://groups.google.com/d/topic/dompdf/MgyHUAVhwr0/discussion

**Comment by samhibberd** [comment] 2016-07-20 14:54
Is there a fix for this?

**Comment by lucianoo6** [comment] 2020-12-31 00:27
infelizmente esse erro e devido a um falta de caractere porem eu uso o @ pra suprimir o erro pois ainda não encontrei outra solução exemplo: 

    `$answerHeader    = @unpack('ntype/nclass/Nttl/nlength', $answerHeaderBin);`

**Comment by bsweeney** [comment] 2021-12-03 18:52
It looks like there are multiple possible causes for this error state per discussion in the forums and information available from #100. Since the linked resources from the OP are no longer available it's difficult to determine the exact cause here.

**Comment by jeliasson** [comment] 2021-12-20 17:03
For anyone else ending up here with the same error, I found @lucianoo6's comment helpful as a workaround. It translates to _"unfortunately this error is due to a lack of character but I use @ to suppress the error because I still haven't found another solution example:"_ 

I donkey-patched this using below. It's not pretty, but it does the job for now.

```bash
# Donkey patch row 218
cat vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php | sed "s/\$a \= unpack/\$a \= \@unpack/g" > ./donkey-patch.php && mv ./donkey-patch.php vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php

# Donkey patch row 219
cat vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php | sed "s/\$v \= \$a\[/\$v \= \@\$a\[/g" > ./donkey-patch.php && mv ./donkey-patch.php vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php

# Verify output of donkey patches
cat vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php | grep '$a = @unpack'
cat vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php | grep '$v = @$a'
```

**Comment by UpperLimits** [comment] 2022-12-08 04:15
Got this error on our Magento2 store and we followed @jeliasson Fix, which worked. Thank you.

**Comment by bsweeney** [comment] 2022-12-08 14:45
If anyone is able to share a font causing the issue we'll take another look.

**Comment by omerkoseoglu** [comment] 2022-12-17 07:41
Example file causing the problem.

[10 Cent Soviet Bold.ttf.zip](https://github.com/dompdf/php-font-lib/files/10251191/10.Cent.Soviet.Bold.ttf.zip)

**Comment by bsweeney** [comment] 2022-12-19 01:27
Can confirm that I get this with the 10 Cent Soviet Bold font. Thanks for the sample.

**Comment by omerkoseoglu** [comment] 2022-12-22 18:08
Its true. "10 Cent Soviet Bold"

**Comment by mleahy-rns** [comment] 2023-02-07 19:41
Is there any update on this issue? I'm running into the same issue but in a slightly different way. The proposed fix of silencing the warning errors does not fix anything. I was originally using dompdf version 1.0.2 and upgraded to version 2.0.3. Neither version addresses this issue.

I'm using a Google font using the following link:
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Questrial" />`

The error is thrown when using the linked stylesheet. However, copying the contents of the stylesheet into a local version seems to work just fine. The linked stylesheet contains 3 URLs to external WOFF2 font files.

**Comment by alex-petrea** [comment] 2023-02-17 10:01
I have the same issue with the font Varela Round - (https://fonts.google.com/specimen/Varela+Round?query=varela) which was working fine until today for the past 3 years.

I tried using it from the local storage and the error persist. I switched to a different font and it works just fine.

**Comment by Webess** [comment] 2023-05-03 08:13
I have the same issue with the font Arimo https://fonts.google.com/specimen/Arimo
Regular (400) font weight is working fine, but other font weights do not work.

**Comment by onepoordeveloper** [comment] 2023-08-22 11:41
Another font causing the issue - [Exmouth](https://www.dafont.com/exmouth.font)
[exmouth_.ttf.zip](https://github.com/dompdf/php-font-lib/files/12408258/exmouth_.ttf.zip)

Resolved by prepending `@` on line 196 & 198
<img width="351" alt="image" src="https://github.com/dompdf/php-font-lib/assets/11477731/b0328391-02c0-43d0-954b-7e14519ea19d">

**Comment by erlangparasu** [comment] 2023-09-15 03:12
still got this issue on 0.5.4

**Comment by atrandafir** [comment] 2023-09-15 12:39
Also started to experience this issue today. I don't know if Google Fonts have changed the way they work but until now all was working fine. I solve it using @jeliasson and @UpperLimits fix, so thanks guys!

**Comment by bmellink** [comment] 2023-09-15 18:36
I had the same issue in readInt16() in lines 218/219 and made the same change:
```
public function readInt16() {
    $a = @unpack("nn", $this->read(2));
    $v = @$a["n"];

    if ($v >= 0x8000) {
      $v -= 0x10000;
    }

    return $v;
  }
```
This change should be considered a temporary solution as this is a bad coding habit that only suppresses an exception. For those wanting to use it, I created a fork at https://github.com/bmellink/php-font-lib with instructions how to change your `composer.json` to use the replacement code.

**Comment by wpmvangroesen** [comment] 2023-09-15 18:56
You can also try to use the code in the pull request #121 . Doesn't use full suppression and seems to work.

**Comment by bsweeney** [comment] 2023-10-21 20:16
Ultimately, this particular message is a symptom not a cause and so not something I would necessarily recommend "fixing" by hiding the error. Looking at the cited fonts I did find a few issues that were caused by fonts that were not fully valid (based on strict reading of the spec) or a deficiency in the php-font-lib is parsing.

**First**, a few fonts had an invalid segment in the cmap table. The particular nature of the invalid data causes the font parser to read past the end of the file. This is, apparently, common enough a problem that other libraries have built in logic to handle the case. php-font-lib should as well, I'm thinking we should ignore 0xFFFF mapping and set other invalid maps to gid 0 (missing glyph).

Initially I'm only handling the attempt to read past the EOF, which I've only encountered so far the 0xFFFF mapping. Ultimately I think we'll want to ensure that the glyph index pointer is within the bounds of the subtable to fully account for potential errors in the cmap data (#127).

References:
- [RazrFalcon/ttf-parser#90](https://github.com/RazrFalcon/ttf-parser/issues/90)
- https://github.com/freetype/freetype/blob/d0cfb4e1b227ce088181627b07619ee08fe6a073/src/sfnt/ttcmap.c#L684-L687

Found in:
- 10 Cent Soviet Bold
- Exmouth
- Monofur

**Second**, php-font-lib was handling zero-byte glyphs incorrectly. The glyph parsing logic always attempted to read the number of contours for a glyph. If the glyph has no representation (e.g. a space), then attempting to read the number of contours would actually:

1. Read the number of contours for the next glyph in the glyf table.
2. Read the first few bytes of the next font table.
3. Read past the end of the font file, if the glyf table is positioned last in the font file and the last glyph had zero data.

The last scenario would be the one to generate the error indicated here. To address this php-font-lib should only attempt to read contours if the glyph has data.

Found in:
- Varela Round

**Lastly**, I didn't encounter any parsing error for some of the cited fonts. If I can't reproduce the error then I can't identify the issue. If anyone experiencing issues with these fonts can provide more details I'll look further.

- Arimo
- Questrial

**One more thing**, I _did_ find an error in the generated font file for some of the fonts. These fonts use the short version loca table (glyph length / 2). The glyph sizes generated by php-font-lib were not padded and, as a result, the lengths recorded in the table for a subsetted font could be invalid. To address this php-font-lib will pad glyphs written to the generated font.

Found in:
- Arimo
- Questrial
- Varela Round

---

As for whether or not to mask file read exceptions, I'm leaning towards not. There are multiple methods that utilize the BinaryStream read methods. It's difficult to say what the impact would be to return empty data universally on failure. Also, php-font-lib is not reading arbitrary chunks from the font file, it is attempting to read file locations based on the direction of the font table data. An error in the read indicates either a parsing error in php-font-lib that we should address or a structural issue in the font file that we should consider handling.

**Comment by maitrecanard** [comment] 2023-11-09 16:11
Hello, I also have this problem but I don't use font, I can't resolve the situation

**Closed** 2023-12-30 16:01 UTC

**Comment by lslqtz** [comment] 2024-02-14 20:49
2024/02/15 04:43:48 [error] 1852#0: *1848 FastCGI sent in stderr: "PHP message: PHP Warning:  unpack(): Type n: not enough input, need 2, have 0 in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 218; PHP message: PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 219; PHP message: PHP Warning:  unpack(): Type n: not enough input, need 2, have 0 in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 218; PHP message: PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 219; PHP message: PHP Warning:  unpack(): Type n: not enough input, need 2, have 0 in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 218; PHP message: PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 219; PHP message: PHP Warning:  unpack(): Type n: not enough input, need 2, have 0 in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 218; PHP message: PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 219; PHP message: PHP Warning:  unpack(): Type n: not enough input, need 2, have 0 in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 218; PHP message: PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 219; PHP message: PHP Warning:  unpack(): Type n: not enough input, need 2, have 0 in /var/www/html/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 196; PHP message: PHP Warning:  Trying to access array offset on value of type bool in /


Same issue, I'm subsetting 40 fonts, so I can't pinpoint which font is causing the problem.
